--
-- PostgreSQL database dump
--

\restrict WlqyMDoZDd3UaXdD8G4l5lt5IWrCO0bxFNGYcuqivAqhp86gLdKOkBGKGdwppiJ

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-06-26 16:38:07

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 4911 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16623)
-- Name: plantas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plantas (
    id bigint NOT NULL,
    conteudo character varying(1000) NOT NULL,
    nome character varying(120) NOT NULL
);


ALTER TABLE public.plantas OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16622)
-- Name: plantas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plantas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plantas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4905 (class 0 OID 16623)
-- Dependencies: 220
-- Data for Name: plantas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plantas (id, conteudo, nome) FROM stdin;
5	Ewé Ogbògbò / Màngò\n“A folha que combate ataques do baixo astral”\n\nFolha quente, descarrego.\nTem funções de energizar, fazer limpeza leve para o dia a dia ou, em banhos específicos, descarregar energias de baixo astral.\n\nÉ associada à ancestralidade feminina, às forças das mães (ìyábás).\nÉ associada a alguns òrìṣà em diferentes nações: Ògún, Òsóòssì, Ìrokó e Èṣù, e também ao òrìṣà Oṣalá.	Folha de manga
4	Èwé Lọ́fíndà / Àrùsò\n\nFolha que traz calma de espírito, acalma o orí, tranquiliza.\nErva fria.\n\nUsado principalmente no culto às Iyabás, como Oxum e Yemanjá.	Lavanda/Alfazema
6	Ewé Òjúṣàjú\n\n“A folha que faz ser o predileto”\n\nÉ uma folha quente e predominantemente masculina. Descarrego.\n\nEla atua energeticamente muito forte e rápido, limpeza profunda e tornando energeticamente atrativo e o predileto.\nPode ser usada em banhos, ofós, fundamentos, sacudimentos e iniciações de alguns òrìṣàs como Ògún, Òsóòsì e Òsányìn. É usada para Èṣù para abertura de caminho.\n\nProteção e discernimento. É a folha conhecida por “enxergar” e repelir más intenções antes que elas atinjam a pessoa.	Guiné
7	- Bom pra diabetes e pros rins\n- Inflamação\n- Doenças reumaticas	Folha de Noni
8	Idà Òrìsà\n\nErva quente.\n\nBom para amor, atrai clientes, torna o ambiente agradável.\nUsada em "lavagem de cabeça e guias", sendo também utilizada em banhos de descarrego.	Espada de ogum
\.


--
-- TOC entry 4912 (class 0 OID 0)
-- Dependencies: 219
-- Name: plantas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plantas_id_seq', 8, true);


--
-- TOC entry 4756 (class 2606 OID 16632)
-- Name: plantas plantas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantas
    ADD CONSTRAINT plantas_pkey PRIMARY KEY (id);


-- Completed on 2026-06-26 16:38:07

--
-- PostgreSQL database dump complete
--

\unrestrict WlqyMDoZDd3UaXdD8G4l5lt5IWrCO0bxFNGYcuqivAqhp86gLdKOkBGKGdwppiJ

