--
-- PostgreSQL database dump
--

\restrict qOCIU8jiac6q6GcnnPacuczLYovIjwdCYl1p4CGrdemqEohUS5Kkc30FrvfsTWT

-- Dumped from database version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: imagens; Type: TABLE; Schema: public; Owner: marcell
--

CREATE TABLE public.imagens (
    id bigint NOT NULL,
    nome_arquivo character varying(255) NOT NULL,
    tamanho bigint NOT NULL,
    tipo character varying(255) NOT NULL,
    url character varying(255) NOT NULL,
    planta_id bigint NOT NULL
);


ALTER TABLE public.imagens OWNER TO marcell;

--
-- Name: imagens_id_seq; Type: SEQUENCE; Schema: public; Owner: marcell
--

ALTER TABLE public.imagens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plantas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.plantas (
    id bigint NOT NULL,
    conteudo character varying(1000) NOT NULL,
    nome character varying(120) NOT NULL
);


ALTER TABLE public.plantas OWNER TO postgres;

--
-- Name: plantas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.plantas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plantas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sassanha_planta; Type: TABLE; Schema: public; Owner: marcell
--

CREATE TABLE public.sassanha_planta (
    sassanha_id bigint NOT NULL,
    planta_id bigint NOT NULL
);


ALTER TABLE public.sassanha_planta OWNER TO marcell;

--
-- Name: sassanhas; Type: TABLE; Schema: public; Owner: marcell
--

CREATE TABLE public.sassanhas (
    id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    yoruba_content text NOT NULL
);


ALTER TABLE public.sassanhas OWNER TO marcell;

--
-- Name: sassanhas_id_seq; Type: SEQUENCE; Schema: public; Owner: marcell
--

ALTER TABLE public.sassanhas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sassanhas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: imagens; Type: TABLE DATA; Schema: public; Owner: marcell
--

COPY public.imagens (id, nome_arquivo, tamanho, tipo, url, planta_id) FROM stdin;
5	arruda1.jpg	35726	image/jpeg	/uploads/e991d40a-6d61-4b3a-b097-eecabcad8cc1.jpg	9
6	alecrim1.jpg	77618	image/jpeg	/uploads/6b65a0b1-4f5a-4f9b-a46b-01afa952dc3f.jpg	33
7	alfavaca1.jpg	104893	image/jpeg	/uploads/393b0924-5903-4e47-8760-d9de87021ea5.jpg	38
8	aroeira1.jpg	108871	image/jpeg	/uploads/6b775b5d-f518-4ffc-9cc4-4f8e848b9b4d.jpg	22
\.


--
-- Data for Name: plantas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.plantas (id, conteudo, nome) FROM stdin;
5	Ewé Ogbògbò / Màngò\n“A folha que combate ataques do baixo astral”\n\nFolha quente, descarrego.\nTem funções de energizar, fazer limpeza leve para o dia a dia ou, em banhos específicos, descarregar energias de baixo astral.\n\nÉ associada à ancestralidade feminina, às forças das mães (ìyábás).\nÉ associada a alguns òrìṣà em diferentes nações: Ògún, Òsóòssì, Ìrokó e Èṣù, e também ao òrìṣà Oṣalá.	Folha de manga
6	Ewé Òjúṣàjú\n\n“A folha que faz ser o predileto”\n\nÉ uma folha quente e predominantemente masculina. Descarrego.\n\nEla atua energeticamente muito forte e rápido, limpeza profunda e tornando energeticamente atrativo e o predileto.\nPode ser usada em banhos, ofós, fundamentos, sacudimentos e iniciações de alguns òrìṣàs como Ògún, Òsóòsì e Òsányìn. É usada para Èṣù para abertura de caminho.\n\nProteção e discernimento. É a folha conhecida por “enxergar” e repelir más intenções antes que elas atinjam a pessoa.	Guiné
7	- Bom pra diabetes e pros rins\n- Inflamação\n- Doenças reumaticas	Folha de Noni
8	Idà Òrìsà\n\nErva quente.\n\nBom para amor, atrai clientes, torna o ambiente agradável.\nUsada em "lavagem de cabeça e guias", sendo também utilizada em banhos de descarrego.	Espada de ogum
9	Ewe Atopá Kun\n\nErva quente\n\nFolha de Exú\n\nPara limpeza e defumações.	Arruda
10	Ewé Ojúùsájú. A Guiné é uma planta dedicada especialmente a Oxóssi, mas também é associada a Ogum e Exú.\n\nSua raiz, em pó, era empregada em uma magia capaz de provocar superexcitação, insônia e alucinações.\nUso de folhas da Guiné de maneira moderada para preparar banhos e pós com finalidades de limpeza, atrair boa sorte e afastar invejas e energias que provocam mal estar e desânimos.\n\nNa medicina caseira, a Guiné possui propriedades antiespasmódicas, diuréticas, sudoríferas e emenagogas, sendo usada em infusões fracas de suas folhas e raízes no tratamento de condições como hidropisia, artrite, reumatismo e malária. Além disso, pode ser utilizada como inseticida.	Guiné
11	Ewé Alubọsa Ayu (casca de alho).\nAyò (ou Ayù) (alho).\nErva quente. Erva de Exú.	Alho
12	Ewé àlùbọ́sà ou Epo àlùbọ́sà\n\nErva quente.	Casca de Cebola
13	Tàbá.\n\nErva quente.	Fumo (tabaco)
4	Èwé Lọ́fíndà / Àrùsò\nErva morna.\nFolha que traz calma de espírito, acalma o orí, tranquiliza.\nUsado principalmente no culto às Iyabás, como Oxum e Yemanjá.	Lavanda/Alfazema
14	Bòtujè Pupa\nErva quente. Erva na força de Ògún, Obalúwàiyé e Oyá.\n\nMedicina popular: Na medicina tradicional, é utilizada devido às suas propriedades cicatrizantes, anti-inflamatórias e analgésicas.	Pinhão Roxo
15	Ewe Pá-nságá.\nErva quente. Folha na linhagem de Ogún	Quebra demanda
16	Èwé Awùrépépé.\nErva fria. É uma das folhas do orô da “voz” do orixá\nOrixás: Exú (flores), Xango, Oxum e Oxalá (folhas).\nTerapêutica: folhas: escorbuto, anemia e dispepsia – extrato das flores: dores de dente – xarope das folhas: expectorante infantil.	Oripepê
17	Èwé Lárà funfun\nErva quente.\nOrixás: Oxalá\nTerapêutica: água das folhas cozidas com sal: inchaços nos pés – sementes: óleo de rícino, que é purgativo e indicado para prisão de ventre.	Mamona Branca
18	Èwé Eucalipto.\nErva quente.	Eucalipto
19	Erva quente.	Folha de chorão
20	Èwé Abéré.\nOrixás: Exú (em pó ou para feitiços) e Oxum.\nTerapêutica: chá – hepatite, febres, males do fígado, rins e bexiga.\nPlanta Muito popular no território nacional, tem sua origem na América tropical e encontra-se presente na Europa e na África. As folhas são também atribuídas a Oxum, com larga utilização em "feitiços". Para esta finalidade são torradas em panelas de ferro, associadas a outros elementos, para a obtenção do Atin (pó), seguindo o modelo mítico de que este orixá é considerado "a mãe dos feitiços". In natura suas folhas são também usadas em assentamentos e trabalhos com Exú.	Picão
21	Erva quente.\nOrixás: Xangô, Ogum e Oxóssi.	Angico
22	Èwé Àjóbi.\nErva quente.\nOrixás: Todos os orixás, mas quando dá fruto, vira para Exú.\nTerapêutica: anti-reumático, bronquites, feridas, tumores, inflamações, corrimentos, diarréias e gastrites.	Aroeira
23	Erva quente.\nOrixás: Ossain e Oxossi.	Jurema Preta
24	Èwé Awó Pupá.\nErva quente.\nOrixás: Ossain, Omolú, Ogum (Ogunjá), Nanã.\nTerapêutica: afecções pulmonares, gripes e resfriados fortes, anginas, faringites e amidalites. Reduzido a pó é aplicado em úlceras e feridas como cicatrizante (uso externo).	Cipó Chumbo
25	Obé Semi Oyá.\nErva quente.\nOrixá: Oyá.\nNativa do México, encontrada em toda América tropical, cultivada ou espontânea em matas sombreadas.\nFolha utilizada no ritual de iniciação dos filhos de Oiá, no àgbo, em banhos purificatórios e sacudimentos. Conhecida também pelo nome nagô OBÉ SEMI OYÁ, nos candomblés do Rio de Janeiro. Os cubanos atribuem essa planta a xangô, Iemanjá e Ogum, e dão-lhe os nomes lucumis peregún, tupa ou diéla (Cabrera 1992:410) Hoehne (1925:68), a respeito desta planta,diz: "Rhoeo discolor, o afamado 'Cordoban" da América Central, a planta mais útil para combater as tosses." Todavia, na medicina rural, esta planta combate também diversos males das vias respiratórias.	Espada-de-Santa-Bárbara
26	Erva quente.	Espinheira Santa
27	Èwé Igí Mésàn.\nErva quente.\nOrixás: Oyá e Xangô.\nTerapêutica: folhas: abortivo, laxante, estimulante intestinal – frutos: hemorróidas, vermes – lenho: feridas, erisipelas e doenças de pele.	Para Raio
28	Èwé Dandà.\nErva quente.\nOrixás: Exu, Ogum, Oxóssi, Ossain, Oxumarê e Nanã.	Dandá da Costa
29	Erva quente.	Comigo ninguém pode
30	Erva quente.	Desata nó
31	Èwé Átáaré.\nErva quente.\nOrixás: Exú e Ossain.\nTerapêutica: tempero de comidas.	Pimentas
32	Èwé Ikiriwí\nErva morna.\nOrixás: Oxalá.\nTerapêutica: chá: gripes e resfriados, febres, afecções leves do estomago, vômitos, escorbuto, corrimentos purulentos da uretra, cólicas menstruais, debilidades sexuais, antiabortivo, antidiabético e regulador da pressão.	Sálvia
34	Erva morna.	Calêndula
35	Èwé Mintí.\nErva morna.	Hortelã
36	Èwé Babá.\nErva morna.\nOrixás: Oxalá.\nTerapêutica: fígado, rins e estomago.	Boldo ou Tapete de Oxalá
37	Èwé Efínrin ou Efínrin Kêkerê\nErva morna.\nOrixás: Oxum, Iemonjá e Oxalá.\nTerapêutica: gases, cólicas intestinais, diarréias, afecções das vias urinárias e/ou respiratórias, gengivites, amidalites, faringites, estomatites, aftas e tempero de comida.	Manjericão
38	Èwé Efínfín.\nErva morna.\nOrixás: Exú (a roxa), Xangô, Omolú e Oxalá.\nTerapêutica: diurético, anti-séptico, calmante, azias, tosses, gripes e resfriados leves, temperos de comida.	Alfavaca
39	Erva morna.\nOrixás: Oxum e Yemoja	Poejo
40	Èwé Eré Tuntún\nErva morna.\nOrixás: Oxum, Iemonjá e Oxalá.	Levante
41	Èwé Eré Túntún.\nErva morna.\nOrixás: Xangô.\nTerapêutica: estimulante do apetite, digestivo, cólicas, flatulência e afrodisíaco.	Manjerona
42	Èwé Òdúndún.\nErva morna.\nOrixás: Oxalá.\nConhecida popularmente por Folha da Costa, saião, folha ou erva grossa. De origem brasileira, esta folha é encontrada em várias lugares de clima tropical e até aclimatada em outros países. Tanto no Brasil como na África, esta planta é dedicada a todos os Orixás ligados a mito da criação, conhecidos como òrìsà-funfun, e por extensão, é utilizada para os demais Orixás. Nos candomblés brasileiros é usada nos rituais de iniciação e obrigações em geral, ligada aos banhos de  àgbo, as oferendas de Eborí, nos sacrifícios de animais cobrindo os olhos dos animais para não ver Ikú, etc. Òdúndún, é a folha que acalma, esfria o Ori, saudada no ritual de sasányìn, é a principal  folha dos filhos de Oxalá. Folha que participa juntamente com outras folhas, do orô da lavagem das vistas e dos búzios dos sacerdotes confirmados por Orunmilá na obrigação de sete anos com direito a utilizarem o Merindilogun.	Folha da Costa ou Saião
43	Erva morna.	Graviola
44	Èwé Igi Itobi\nErva morna.	Abacateiro
45	Èwé Tótó\nErva morna.\nOrixás: Oxum, Nanã, Yemoja.	Colônia
46	Èwé Abámọdá\nErva morna.\nOrixás: Exú, Oxalá, Xangô e orixás fun fun.\nTerapêutica: refrigerante, diurética e sedativa. Combate cefaléias, nevralgias, dor de dente, coqueluche e afecções das vias respiratórias. Eficiente contra as doenças de pele, feridas purulentas, furúnculos, úlceras e dermatoses.\nÁbámodá, segundo Dalziel (1948:28), em dialeto yorubá significa "o que você deseja, você faz"; todavia, quando chamada de  erú òdúndún (escravo de odundun), é considerada como folha subordinada e afim, que pode eventualmente substituir o òdúndún (Kalanchoe crenata (Andr.) Haw), segundo a cosmovisão jêje-nagô.	Fortuna
47	Capeba Èwé Ìyá.\nErva morna.\nOrixás: Iemonjá.\nTerapêutica: estimulante, diurético, afecções das vias renais, febres, gastrites, debilidades orgânicas, furúnculos, abscessos, prisão de ventre, ingurgitamento do fígado e baço, ulcerações sifilíticas, hemorróidas e reumatismo.	Capeba
48	Èwé Rínrín.\nErva morna.\nOrixás: Oxum e Oxalá.\nTerapêutica: irritações e inflamações oculares e suave tônico cardíaco.	Oriri
49	Èwé Ewúro\nErva morna.\nOrixás: Ogum.\nTerapêutica: sumo: enjôos provocados por má digestão ou problemas hepáticos.	Boldo Paulista, Boldo Baiano ou Alumã
50	Erva morna.	Goiabeira
51	Èwé Itá\nOrixás: Antes de 18h é de Exú, após 18h, vira pra Egun.\nTerapêutica: adstringente, anti-reumático, diarréias e febres infantis, gripes e resfriados, tosses.	Pitangueira
52	Erva morna.\nOrixás: Oxum, Oxóssi e Oyá.	Laranjeira
53	Èwé Lorogún.\nErva morna.\nOrixás: Ogum.	Abre Caminho
54	Èwé Òmun\nErva morna.\nOrixás: Osumarê.	Samambaia de poço ou Pente de cobra
55	Erva morna.	Angélica
56	Èwé Irùngbòn\nErva morna.\nOrixás: Omolú.\nTerapêutica: abscessos, hemorróidas, reumatismo.	Barba de velho
57	Erva morna.	Cipó Caboclo
58	Erva morna.\nOrixás: Nanã, Oxóssi e Obaluayê	Ipê Roxo
59	Erva morna.	Rosa Branca
60	Erva morna.	Folha de cenoura
61	Erva morna.	Folha de beterraba
33	Èwé Ewéré\nErva morna.\nOrixás: Oxóssi e Oxalá.\nTerapêutica: má digestão, gases, reumatismo, encefalia e tempero de comida. Também conhecido por efeitos estimulantes antioxidantes, associados à melhora da memória, foco e concentração.	Alecrim
\.


--
-- Data for Name: sassanha_planta; Type: TABLE DATA; Schema: public; Owner: marcell
--

COPY public.sassanha_planta (sassanha_id, planta_id) FROM stdin;
1	42
\.


--
-- Data for Name: sassanhas; Type: TABLE DATA; Schema: public; Owner: marcell
--

COPY public.sassanhas (id, content, created_at, updated_at, yoruba_content) FROM stdin;
1	Odundun Pai espalhe sua calma\nOdundun Pai espalhe sua calma\nGrande espírito, espalhe sua calma\nOdundun Pai, espalhe sua calma	2026-07-01 02:35:12.912481	2026-07-01 02:35:12.912504	Ewé Òdúndún\nÒdúndún Bàbá t’èrò re\nÒdúndún Bàbá t’èrò re\nBàbá t’èro lé\nMonlé t’ero re\nÒdúndún Bàbá t’ero re
\.


--
-- Name: imagens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcell
--

SELECT pg_catalog.setval('public.imagens_id_seq', 8, true);


--
-- Name: plantas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.plantas_id_seq', 61, true);


--
-- Name: sassanhas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: marcell
--

SELECT pg_catalog.setval('public.sassanhas_id_seq', 1, true);


--
-- Name: imagens imagens_pkey; Type: CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.imagens
    ADD CONSTRAINT imagens_pkey PRIMARY KEY (id);


--
-- Name: plantas plantas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.plantas
    ADD CONSTRAINT plantas_pkey PRIMARY KEY (id);


--
-- Name: sassanha_planta sassanha_planta_pkey; Type: CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.sassanha_planta
    ADD CONSTRAINT sassanha_planta_pkey PRIMARY KEY (sassanha_id, planta_id);


--
-- Name: sassanhas sassanhas_pkey; Type: CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.sassanhas
    ADD CONSTRAINT sassanhas_pkey PRIMARY KEY (id);


--
-- Name: sassanha_planta fk4syyf8qkigfsahssvp92jfgyq; Type: FK CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.sassanha_planta
    ADD CONSTRAINT fk4syyf8qkigfsahssvp92jfgyq FOREIGN KEY (planta_id) REFERENCES public.plantas(id);


--
-- Name: imagens fkjv58fyfrvxfgbn80r08v2c5ry; Type: FK CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.imagens
    ADD CONSTRAINT fkjv58fyfrvxfgbn80r08v2c5ry FOREIGN KEY (planta_id) REFERENCES public.plantas(id);


--
-- Name: sassanha_planta fkmtl8hr6kmm5y8serpujxftx39; Type: FK CONSTRAINT; Schema: public; Owner: marcell
--

ALTER TABLE ONLY public.sassanha_planta
    ADD CONSTRAINT fkmtl8hr6kmm5y8serpujxftx39 FOREIGN KEY (sassanha_id) REFERENCES public.sassanhas(id);


--
-- PostgreSQL database dump complete
--

\unrestrict qOCIU8jiac6q6GcnnPacuczLYovIjwdCYl1p4CGrdemqEohUS5Kkc30FrvfsTWT

