spring.application.name=plantas

# datasource PostgreSQL
spring.datasource.url = jdbc:postgresql://localhost:5433/plantas
spring.datasource.username=plantas
spring.datasource.password=plantas

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# app
ai.provider=gemini