spring.application.name=plantas

# datasource PostgreSQL
spring.datasource.url = jdbc:postgresql://localhost:5433/plantas
spring.datasource.username=plantas
spring.datasource.password=plantas

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# ai
#gemini | groq
ai.provider=groq
#groq
ai.groq.api-key=${GROQ_API_KEY}
ai.groq.base-url=https://api.groq.com/openai/v1
ai.groq.model=llama-4-scout-17b-16e-instruct
#gemini
ai.gemini.api-key=${GEMINI_API_KEY}
ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
ai.gemini.model=gemini-2.0-flash