spring.application.name=plantas

# datasource PostgreSQL
spring.datasource.url = jdbc:postgresql://localhost:5432/herbario
spring.datasource.username=postgres
spring.datasource.password=root

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
upload.dir=uploads

# ai
#gemini | groq
ai.provider=gemini
#groq
ai.groq.api-key=${GROQ_API_KEY}
ai.groq.base-url=https://api.groq.com/openai/v1
ai.groq.model=llama-4-scout-17b-16e-instruct
#gemini
ai.gemini.api-key=${HERBARIO_GEMINI_API_KEY}
ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
ai.gemini.model=gemini-2.5-flash