# Plantas
### Listar todas as plantas
GET http://localhost:8080/plantas

### Buscar planta por ID
GET http://localhost:8080/plantas/1

### Criar planta
POST http://localhost:8080/plantas
Content-Type: application/json

{
    "nome": "Planta 1",
    "conteudo": "Conteudo da planta 1"
}

### Atualizar planta
PATCH http://localhost:8080/plantas/1
Content-Type: application/json

{
    "nome": "Planta 1 atualizada",
    "conteudo": "Conteudo da planta 1 atualizado"
}

### Deletar planta
DELETE http://localhost:8080/plantas/1

# AI

### Analisar planta
POST http://localhost:8080/ai
Content-Type: application/json

{
    "nomes": ["Alecrim", "Boldo", "Manjericão"],
    "intencao": "Banho de descarrego"
}

### Pesquisa avançada

GET http://localhost:8080/api/search/avancada?conteudo=quente

### Pesquisa semântica

POST http://localhost:8080/api/search/semantica
Content-Type: application/json

{
    "query": "plantas para relaxamento"
}